#!/bin/sh

cd /home/eugene/projects/auto_tsandripsh_hotel/

f=./_build/gallery_info.ml


echo "include Gallery_info_make" > $f
echo >> $f
echo "let () =" >> $f
jpeginfo gallery/*.jpg | awk '{print "add \"/"$1"\" "$2" "$4";"}' >> $f
echo "()" >> $f

